### ISSUE TITLE
CybroScgiServer installation fails

### ISSUE THREAD

**Issue by DarkWingRo** [killer0071234/ha-addon-repository#52]
# Problem/Motivation
Installation fails with non-zero code on a Rpi4
After SCGI Server was running normaly for a while and HA could access the variable on my CYBRO-3 PLC, it somewhen stopped working after an HA update. I then wanted to reinstall the AddOn but that now always fails. 
There have been some more HA updates since then.

## Expected behavior
Install Cybro SCGI Server

## Actual behavior
Installation of AddOn Fails with non-zero code:

Add-on konnte nicht installiert werden
The command '/bin/bash -o pipefail -c apk add --no-cache --virtual .build-dependencies build-base=0.5-r3 libffi-dev=3.4.4-r2 py3-wheel=0.40.0-r1 python3-dev=3.11.4-r0 && apk add --no-cache py3-bcrypt=4.0.1-r2 py3-cryptography=40.0.2-r1 py3-pip=23.1.2-r0 python3=3.11.4-r0 nginx=1.24.0-r6 && pip install -r /tmp/requirements.txt && find /usr \( -type d -a -name test -o -name tests -o -name '__pycache__' \) -o \( -type f -a -name '*.pyc' -o -name '*.pyo' \) -exec rm -rf '{}' + && apk del --no-cache --purge .build-dependencies' returned a non-zero code: 63

Sometimes it also fails with code 5

## Steps to reproduce
Just press Install - fails most times with code 63 and sometimes with code 5
Rebooting the device several times didn't change anything.

Thx in advance,
Robert

**Comment by killer0071234** [comment]
Thanks for your report

I am working on a solution.

BR Daniel

**Comment by killer0071234** [comment]
Can you try to update to the 0.1.3 of that addon?

**Comment by DarkWingRo** [comment]
Hello Daniel,
Version 0.1.3 did the trick. 
The AddOn is installed again and the HIQ Home integration can fetch the data again.
Thx for your quick support!
kr
Robert
