### ISSUE TITLE
installation error on raspberry pi

### ISSUE THREAD

**Issue by pipesmoker300** [killer0071234/ha-addon-repository#55]
Hallo,

I wanted to install via your repository and got this error:

Add-on konnte nicht installiert werden
The command '/bin/bash -o pipefail -c apk add --no-cache --virtual .build-dependencies build-base=0.5-r3 libffi-dev=3.4.4-r2 py3-wheel=0.40.0-r1 python3-dev=3.11.5-r0 && apk add --no-cache py3-bcrypt=4.0.1-r2 py3-cryptography=41.0.3-r0 py3-pip=23.1.2-r0 python3=3.11.5-r0 nginx=1.24.0-r6 && pip install -r /tmp/requirements.txt && find /usr \( -type d -a -name test -o -name tests -o -name '__pycache__' \) -o \( -type f -a -name '*.pyc' -o -name '*.pyo' \) -exec rm -rf '{}' + && apk del --no-cache --purge .build-dependencies' returned a non-zero code: 63

Raspberry pi 4, 4GB

Could you please help me?

Thank you in advance!

Kind regards
Joachim 

# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by killer0071234** [comment]
Hi,

There were some changes on the HA base addon image.

please use the latest HA addon v0.1.4

this should work.

BR Daniel
__

**Comment by pipesmoker300** [comment]
Thank you Daniel for the fast update!
This worked for me

kind regards,
Joachim
